[provider]
type = "electrs" # "electrs" | "bitcoin-core" default: "electrs"
async = true # default: false

[electrs]
url = "http://100.90.20.1:3000" # default: "https://mempool.space/api"

[bitcoin_core]
url = "http://127.0.0.1:8332" # default: ""
user = "bitcoin" # default: ""
password = "bitcoin" # default: ""

[block]
threshold = 0.1 # default: 0.1

[output]
csv_file = "results.csv" # default: ""
debug_file = "debug.log" # default: ""
html_file = "report.html" # default: ""
