[provider]
type = "esplora" # "esplora" | "bitcoin-core"

[esplora]
url = "https://mempool.space/api"

[bitcoin_core]
rpc_url  = "http://127.0.0.1:8332"
rpc_user = "user"
rpc_password = "password"

[block]
threshold = 0.1
async     = false

[output]
csv_file = "results.csv"
